name: Planet Suitcase
favicon: null
layout_spectrum: 0.5055693727917969
typography_spectrum: 0.19616361777298152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#b3cde8'
    - '#8c8c8c'
    - '#0b0e00'
  brandStrength: 0.75483746570535
  lightness: 0.7657197245862335
  saturation: 0.07711455971002579
  rhythmicContrast: 0.3716582441702485
purpose: []
